### ISSUE TITLE
As a user I want to authenticate in order to access the system

### ISSUE THREAD

**Issue by marceljar** [marceljar/Group_00#5]
### Description
An authentication system will be implemented using Django's authentication support tools provided in django.contrib.auth. This will be a full-stack implementation. A form will be provided for the user to enter his/her information on the browser. After an HTTPS request is made to the back-end, the user will either be granted access (and a session is created), or receive a message warning that the credentials were incorrect.
 
### Acceptance Criteria

- Users should be able to log in to the system using proper credentials created using strong password rules
- Wrong credentials should result in an error message
- Upon login, users should be redirected to a proper page
- A successful login should maintain session across different pages

### Testing Criteria
For testing purposes, a few users will be added to the database. Then, logins attempts will be made with:
- correct credentials
- right user name and wrong password
- wrong username

Also, you should make sure that users cannot access credentials-protected pages by simply entering the proper URLs (without a previous login)

**Comment by pouria-honarmand** [comment]
> ### User Story
> _As a user I want to authenticate in order to access the system_ [how to write a user story](https://www.atlassian.com/agile/project-management/user-stories)
> 
> ### Description
> An authentication system will be implemented using Django's authentication support tools provided in django.contrib.auth. This will be a full-stack implementation. A form will be provided for the user to enter his/her information on the browser. After an HTTPS request is made to the back-end, the user will either be granted access (and a session is created), or receive a message warning that the credentials were incorrect.
> 
> ### Acceptance Criteria
> * Users should be able to log in to the system using proper credentials created using strong password rules
> * Wrong credentials should result in an error message
> * Upon login, users should be redirected to a proper page
> * A successful login should maintain session across different pages
> 
> ### Testing
> For testing purposes, a few users will be added to the database. Then, logins attempts will be made with:
> 
> * correct credentials
> * right user name and wrong password
> * wrong username
>   Also, you should make sure that users cannot access credentials-protected pages by simply entering the proper URLs (without a previous login)



> ### User Story
> _As a user I want to authenticate in order to access the system_ [how to write a user story](https://www.atlassian.com/agile/project-management/user-stories)
> 
> ### Description
> An authentication system will be implemented using Django's authentication support tools provided in django.contrib.auth. This will be a full-stack implementation. A form will be provided for the user to enter his/her information on the browser. After an HTTPS request is made to the back-end, the user will either be granted access (and a session is created), or receive a message warning that the credentials were incorrect.
> 
> ### Acceptance Criteria
> * Users should be able to log in to the system using proper credentials created using strong password rules
> * Wrong credentials should result in an error message
> * Upon login, users should be redirected to a proper page
> * A successful login should maintain session across different pages
> 
> ### Testing
> For testing purposes, a few users will be added to the database. Then, logins attempts will be made with:
> 
> * correct credentials
> * right user name and wrong password
> * wrong username
>   Also, you should make sure that users cannot access credentials-protected pages by simply entering the proper URLs (without a previous login)
